service: rs-input-fetcher
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  profile: na_staging
  stage: global
  memorySize: 128
  vpc:
    securityGroupIds:
      - sg-c54d7c8c
    subnetIds:
      - subnet-e10b0db9
      - subnet-17d4225e
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  fetch_elsm_acct:
    handler: bin/fetcher
    events:
      - schedule: rate(45 minutes)
    environment:
      MYSQL_CONNECTION_STRING: ${env:LIVE_MYSQL_CONNECTION_STRING}
      RS_REFRESH_TOKEN: ${env:RS_REFRESH_TOKEN}
      RS_ACCOUNT_ID: ${env:RS_ACCOUNT_ID}
    timeout: 300